# Generated by Django 2.2.2 on 2019-06-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('highlight_1', models.CharField(blank=True, max_length=100, null=True)),
                ('highlight_2', models.CharField(blank=True, max_length=100, null=True)),
                ('highlight_3', models.CharField(blank=True, max_length=100, null=True)),
                ('highlight_4', models.CharField(blank=True, max_length=100, null=True)),
                ('highlight_5', models.CharField(blank=True, max_length=100, null=True)),
                ('highlight_6', models.CharField(blank=True, max_length=100, null=True)),
                ('highlight_7', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categpry', to='category.Category')),
            ],
        ),
    ]
