# Generated by Django 2.2.2 on 2019-06-27 12:11

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_location', models.CharField(max_length=200)),
                ('cover_image', cloudinary.models.CloudinaryField(max_length=255)),
                ('image_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('image_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.Category')),
            ],
        ),
    ]
