# Generated by Django 2.2.2 on 2019-06-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.CharField(choices=[('featured', 'Featured'), ('not_featured', 'Not Featured')], default='not_featured', max_length=50),
        ),
    ]
